#!/bin/bash

r= lsb_release -r | awk '{print($2)}'

if $r > '12.10' ; then
cp /usr/share/ya-gui/Расшарить* /home/*/.local/share/nautilus/scripts
else
cp /usr/share/ya-gui/Расшарить* /home/*/.gnome2/nautilus-scripts
fi
