#!/bin/bash

if (("`lsb_release -r | sed -n '1{s/[^0-9]//g;p;q}'`" > "1210")); then
cd $HOME/.local/share/nautilus/scripts/
rm -rf SEND-TO-YANDEX
else
cd $HOME/.gnome2/nautilus-scripts/
rm -rf SEND-TO-YANDEX
fi
exit 0
